"""The pinned gateway registry data path and the dev-check presence
rule (the overlay trigger), plus the promote
retarget note for gateway-effort generation moves.

Every test reads the frozen registry fixture ``tests/fixtures/registry``
(cut by ``tests/fixtures/cut_registry_fixture.py``) through
``CLAUDE_MULTI_REGISTRY_DIR`` and the frozen catalog fixture — never the
real pinned registry and never the shipped catalog.
"""

from __future__ import annotations

import copy
import hashlib
import io
import json
import os
import shutil
import tempfile
import unittest
from contextlib import redirect_stdout
from pathlib import Path
from unittest import mock

from claude_multi import account_pools, catalog, dev
from _catalog import FIXTURE_ROOT, uses_shipped_catalog
from _layout import REGISTRY_SNAPSHOT, REPO_ROOT, RESOURCES_ROOT, fake_checkout

REGISTRY_FIXTURE = REPO_ROOT / "tests" / "fixtures" / "registry"


def _oauth_lines(raw_docs):
    providers = raw_docs["providers"]["providers"]
    return {
        key: line
        for key, line in raw_docs["models"]["models"].items()
        if catalog.registry_section(providers[line["provider"]]) is not None
    }


# The pinned upstream registry snapshot (generated by `tools/build.py gateway
# registry` from the pinned source; the Nix package build compares it with
# that source byte for byte). A gateway re-pin regenerates it and updates
# these recorded identities in the same change.
REGISTRY_SNAPSHOT_SHA256 = {
    "models.json": "ca457e5269f67068fcd13de77a4eb55da603917cd77309e61e4661ef4327c85b",
    "codex_client_models.json": "7b15fec55ed279c2a0f4b6dfd1f7d2617d7c9f22e94d385242a8cd9534411d38",
}


class RegistryDirTests(unittest.TestCase):
    def test_env_override_and_explicitly_absent_directory(self) -> None:
        self.assertEqual(
            catalog.registry_dir({catalog.REGISTRY_DIR_ENV: str(REGISTRY_FIXTURE)}),
            REGISTRY_FIXTURE,
        )
        self.assertIsNone(
            catalog.registry_dir({catalog.REGISTRY_DIR_ENV: str(REGISTRY_FIXTURE / "nope")})
        )

    def test_the_packaged_snapshot_is_the_default(self) -> None:
        # Resources carry the pinned snapshot: no override selects it.
        self.assertEqual(catalog.registry_dir({}), RESOURCES_ROOT / "registry")
        self.assertEqual(REGISTRY_SNAPSHOT, RESOURCES_ROOT / "registry")
        registry = catalog.load_pinned_registry(catalog.registry_dir({}))
        # Every account pool's sections are in the pinned registry.
        for pool in account_pools.pools().values():
            with self.subTest(pool=pool.name):
                self.assertLessEqual(set(pool.registry_sections), set(registry.sections))

    def test_an_explicit_resource_root_selects_its_own_registry(self) -> None:
        # Resources follow the selected root: explicit > CLAUDE_MULTI_ASSETS >
        # packaged. The frozen fixture root carries none.
        self.assertIsNone(catalog.registry_dir({}, FIXTURE_ROOT))
        self.assertIsNone(catalog.registry_dir({"CLAUDE_MULTI_ASSETS": str(FIXTURE_ROOT)}))
        self.assertEqual(catalog.registry_dir({"CLAUDE_MULTI_ASSETS": str(FIXTURE_ROOT)}, RESOURCES_ROOT),
                         RESOURCES_ROOT / "registry")
        self.assertEqual(catalog.registry_dir({catalog.REGISTRY_DIR_ENV: str(REGISTRY_FIXTURE)}, RESOURCES_ROOT),
                         REGISTRY_FIXTURE)


class RegistrySnapshotTests(unittest.TestCase):
    """The checked-in snapshot keeps its recorded identity (one content
    authority: the pinned upstream source, through the build tool)."""

    def test_recorded_identity(self) -> None:
        self.assertEqual(sorted(path.name for path in REGISTRY_SNAPSHOT.iterdir()),
                         sorted(catalog.REGISTRY_FILES))
        for name, digest in REGISTRY_SNAPSHOT_SHA256.items():
            with self.subTest(name=name):
                self.assertEqual(hashlib.sha256((REGISTRY_SNAPSHOT / name).read_bytes()).hexdigest(), digest)
        self.assertEqual(set(REGISTRY_SNAPSHOT_SHA256), set(catalog.REGISTRY_FILES))

    def test_the_build_tool_and_the_package_name_the_same_files(self) -> None:
        from _layout import BUILD_TOOL, NIX_DIR, load_tool

        build = load_tool("build")
        self.assertEqual(Path(BUILD_TOOL).name, "build.py")
        self.assertEqual(build.DEFAULT_REGISTRY, REGISTRY_SNAPSHOT)
        self.assertEqual(build.REGISTRY_FILES, catalog.REGISTRY_FILES)
        package = (NIX_DIR / "package.nix").read_text()
        self.assertIn("for name in " + " ".join(catalog.REGISTRY_FILES) + "; do", package)
        self.assertIn('cmp -s "${cliProxyApiRegistry}/$name"', package)

    @unittest.skipUnless(os.environ.get("CLAUDE_MULTI_TEST_UPSTREAM_SOURCE"),
                         "BOUNDARY: CLAUDE_MULTI_TEST_UPSTREAM_SOURCE names no pinned upstream source tree")
    def test_snapshot_equals_the_pinned_source(self) -> None:
        source = Path(os.environ["CLAUDE_MULTI_TEST_UPSTREAM_SOURCE"]) / "internal" / "registry" / "models"
        for name in catalog.REGISTRY_FILES:
            with self.subTest(name=name):
                self.assertEqual((REGISTRY_SNAPSHOT / name).read_bytes(), (source / name).read_bytes())


class PinnedRegistryTests(unittest.TestCase):
    def setUp(self) -> None:
        self.registry = catalog.load_pinned_registry(REGISTRY_FIXTURE)
        self.raw = catalog.load_raw(FIXTURE_ROOT)["docs"]

    def test_sections_and_codex_metadata(self) -> None:
        self.assertIn("claude", self.registry.sections)
        self.assertIn(account_pools.pool("codex").registry_section, self.registry.sections)
        # Retirement data stays reachable for the doctor radar.
        retiring = {
            slug: fields["retirement_at"]
            for slug, fields in self.registry.codex.items()
            if fields["retirement_at"]
        }
        self.assertEqual(retiring, {"gpt-5.5": "2026-10-14T19:00:00Z"})
        self.assertEqual(self.registry.codex["gpt-5.5"]["upgrade"], "gpt-5.6-sol")
        self.assertEqual(self.registry.codex["gpt-5.5"]["visibility"], "list")

    def test_only_oauth_pools_have_a_section(self) -> None:
        providers = self.raw["providers"]["providers"]
        sections = {pid: catalog.registry_section(p) for pid, p in providers.items()}
        for pid, provider in providers.items():
            with self.subTest(provider=pid):
                if provider["transport"]["kind"] == "oauth-pool":
                    self.assertIsNotNone(sections[pid])
                else:
                    self.assertIsNone(sections[pid])
        codex = [p for p in providers.values() if p["transport"].get("pool") == "codex"]
        self.assertTrue(codex)
        self.assertEqual(catalog.registry_section(codex[0]), "codex-pro")

    def test_fixture_catalog_is_fully_present(self) -> None:
        self.assertTrue(_oauth_lines(self.raw))
        self.assertEqual(
            catalog.registry_absent_wires(
                self.raw["models"]["models"], self.raw["providers"]["providers"], self.registry
            ),
            [],
        )

    def test_absent_wire_is_flagged_new_lines_included(self) -> None:
        models = copy.deepcopy(self.raw["models"]["models"])
        providers = self.raw["providers"]["providers"]
        key = sorted(_oauth_lines(self.raw))[0]
        models[key]["wire_model"] = "wire-the-registry-lacks"
        models[key]["status"] = "new"
        section = catalog.registry_section(providers[models[key]["provider"]])
        self.assertEqual(
            catalog.registry_absent_wires(models, providers, self.registry),
            [(key, "wire-the-registry-lacks", section)],
        )

    def test_tier_matters(self) -> None:
        # The fixture keeps the pinned tier difference: codex-free lacks a
        # wire codex-pro carries, so the rule reads codex-pro only.
        free = self.registry.sections["codex-free"]
        pro = self.registry.sections["codex-pro"]
        self.assertTrue(pro - free)

    def test_malformed_registry_raises(self) -> None:
        root = Path(tempfile.mkdtemp(prefix="claude-multi-registry-"))
        self.addCleanup(lambda: shutil.rmtree(root, ignore_errors=True))
        for models, codex in (
            ("[]", '{"models": []}'),
            ('{"claude": {}}', '{"models": []}'),
            ('{"claude": []}', '{"nope": []}'),
            ("not json", '{"models": []}'),
        ):
            with self.subTest(models=models, codex=codex):
                (root / "models.json").write_text(models)
                (root / "codex_client_models.json").write_text(codex)
                with self.assertRaises(catalog.CatalogError):
                    catalog.load_pinned_registry(root)


class RegistryMetaTests(unittest.TestCase):
    """Bounded, advisory ``PinnedRegistry.meta``."""

    def write(self, models: dict, codex: dict | None = None) -> Path:
        root = Path(tempfile.mkdtemp(prefix="claude-multi-registry-meta-"))
        self.addCleanup(lambda: shutil.rmtree(root, ignore_errors=True))
        (root / "models.json").write_text(json.dumps(models))
        (root / "codex_client_models.json").write_text(json.dumps(codex or {"models": []}))
        return root

    def test_fixture_meta_matches_the_frozen_cut(self) -> None:
        registry = catalog.load_pinned_registry(REGISTRY_FIXTURE)
        raw = json.loads((REGISTRY_FIXTURE / "models.json").read_text())
        for section, items in raw.items():
            self.assertEqual(set(registry.meta[section]), registry.sections[section])
            for item in items:
                with self.subTest(section=section, wire=item["id"]):
                    meta = registry.meta[section][item["id"]]
                    self.assertEqual(meta.context_length, item.get("context_length"))
                    self.assertEqual(meta.max_completion_tokens, item.get("max_completion_tokens"))
                    self.assertEqual(meta.created, item.get("created"))
                    self.assertEqual(meta.display_name, item.get("display_name"))

    def test_malformed_fields_are_none_and_sections_unchanged(self) -> None:
        good = {"id": "wire-a", "display_name": "Wire A", "context_length": 400000,
                "max_completion_tokens": 64000, "created": 1790000000,
                "thinking": {"levels": ["low", "high", "xhigh"]}}
        bad = {"id": "wire-b", "display_name": "x" * 97, "context_length": True,
               "max_completion_tokens": 2**31, "created": -1, "thinking": {"levels": ["high", "turbo"]}}
        control = {"id": "wire-c", "display_name": "evil\x1b[31m", "context_length": "400000",
                   "created": 1.5, "thinking": {"levels": "high"}}
        empty = {"id": "wire-d", "display_name": " ", "thinking": {"levels": []}}
        dup = {"id": "wire-e", "thinking": {"levels": ["high", "high"]}}
        root = self.write({"claude": [good, bad, control, empty, dup, {"id": "../bad"}, "junk"]})
        registry = catalog.load_pinned_registry(root)
        self.assertEqual(registry.sections["claude"], frozenset({"wire-a", "wire-b", "wire-c", "wire-d", "wire-e"}))
        self.assertEqual(registry.meta["claude"]["wire-a"], catalog.RegistryModel(
            "Wire A", 400000, 64000, ("low", "high", "xhigh"), 1790000000))
        for wire in ("wire-b", "wire-c", "wire-d", "wire-e"):
            with self.subTest(wire=wire):
                self.assertEqual(registry.meta["claude"][wire], catalog.RegistryModel())

    def test_conflicting_duplicates_keep_presence_and_become_unknown(self) -> None:
        first = {"id": "wire-a", "display_name": "A", "context_length": 400000, "created": 10,
                 "thinking": {"levels": ["high"]}}
        second = {"id": "wire-a", "display_name": "A", "context_length": 272000, "created": 10,
                  "thinking": {"levels": ["high", "xhigh"]}}
        registry = catalog.load_pinned_registry(self.write({"codex-pro": [first, second]}))
        self.assertIn("wire-a", registry.sections["codex-pro"])
        self.assertEqual(registry.meta["codex-pro"]["wire-a"],
                         catalog.RegistryModel("A", None, None, None, 10))

    def test_codex_upgrade_metadata_is_untouched(self) -> None:
        codex = {"models": [{"slug": "wire-a", "visibility": "hide", "upgrade": {"model": "wire-b"}}]}
        registry = catalog.load_pinned_registry(self.write({"codex-pro": [{"id": "wire-a"}]}, codex))
        self.assertEqual(registry.codex["wire-a"], {"visibility": "hide", "upgrade": "wire-b", "retirement_at": None})

    def test_meta_is_advisory_only(self) -> None:
        # No registry value becomes a context validation, contract, admission
        # or fence input: the catalog modules that own those never read meta.
        for module in ("profile.py", "scope.py", "compiler.py", "settings.py", "render.py"):
            with self.subTest(module=module):
                text = (REPO_ROOT / "src" / "claude_multi" / module).read_text()
                self.assertNotIn(".meta[", text)
                self.assertNotIn("RegistryModel", text)


class PresenceRuleTests(unittest.TestCase):
    def setUp(self) -> None:
        self.raw = catalog.load_raw(FIXTURE_ROOT)["docs"]
        self.env = {catalog.REGISTRY_DIR_ENV: str(REGISTRY_FIXTURE)}

    def test_clean_catalog_reports_all_present(self) -> None:
        lines = dev.registry_presence(self.raw, self.env)
        self.assertEqual(len(lines), 1)
        self.assertIn("every OAuth-pool line wire is in the pinned gateway registry", lines[0])

    def test_absent_wire_is_reported_not_refused(self) -> None:
        docs = copy.deepcopy(self.raw)
        key = sorted(_oauth_lines(docs))[0]
        docs["models"]["models"][key]["wire_model"] = "wire-the-registry-lacks"
        lines = dev.registry_presence(docs, self.env)
        self.assertEqual(len(lines), 1)
        self.assertIn(repr(key), lines[0])
        self.assertIn("'wire-the-registry-lacks'", lines[0])
        self.assertIn("until a registry patch or registry_overlay lands", lines[0])

    def test_missing_registry_skips_with_a_line(self) -> None:
        # An explicitly absent registry directory (the packaged resources
        # carry the snapshot, so an empty environment is no longer absence).
        absent = {catalog.REGISTRY_DIR_ENV: str(REGISTRY_FIXTURE / "absent")}
        lines = dev.registry_presence(self.raw, absent)
        self.assertEqual(len(lines), 1)
        self.assertIn("presence rule skipped", lines[0])

    def test_the_packaged_snapshot_runs_the_rule_by_default(self) -> None:
        lines = dev.registry_presence(self.raw, {})
        self.assertTrue(lines)
        self.assertFalse(any("presence rule skipped" in line for line in lines), lines)

    def test_check_carries_and_prints_the_rule(self) -> None:
        root = Path(tempfile.mkdtemp(prefix="claude-multi-registry-check-"))
        os.chmod(root, 0o700)
        self.addCleanup(lambda: shutil.rmtree(root, ignore_errors=True))
        repo = fake_checkout(root / "repo", FIXTURE_ROOT)
        draft = dev.make_model_draft(
            name="d1",
            provider="openai",
            entry={
                "id": "newmodel",
                "provider": "openai",
                "display": "New Model",
                "generation": "1",
                "wire_model": "gpt-new",
                "capabilities": ["agents"],
                "roles": ["cm-reviewer"],
                "context": {
                    "client_tokens": 128000, "provider_tokens": 128000,
                    "scalar_tokens": 128000, "ordinary_profile": None,
                    "declared_tokens": 128000, "validated_tokens": 128000,
                    "qualification": "registry test fixture",
                },
                "efforts": {"high": {"selector": "gpt-multi-newmodel-high",
                                     "proxy_contract": "reasoning-effort-high"}},
                "default_effort": "high",
                "lead": None,
                "routing_note": "Fixture model for the registry rule.",
                "minimum_tested": {"claude_code": "2.1.216", "cliproxyapi": "7.3.15"},
                "status": "new",
                "registry_overlay": None,
            },
            now="2026-09-26T00:00:00Z",
        )
        with mock.patch.dict(os.environ, self.env):
            result = dev.check_draft(
                draft, repo=repo, runner=lambda c, w: {"cmd": c, "returncode": 0},
                candidate_parent=Path(tempfile.mkdtemp(dir=root)),
            )
        self.assertEqual(len(result.registry), 1)
        self.assertIn("'newmodel' wire 'gpt-new' is absent", result.registry[0])
        self.assertIn("'codex-pro'", result.registry[0])
        store = dev.DraftStore(root / "state" / "claude-multi" / "drafts")
        store.save("d1", draft)
        out = io.StringIO()
        with mock.patch.dict(os.environ, {**self.env, "XDG_STATE_HOME": str(root / "state")}), \
                mock.patch.object(dev, "_default_runner",
                                  lambda c, w: {"cmd": c, "returncode": 0}), \
                redirect_stdout(out):
            self.assertEqual(dev.main(["check", "d1", "--repo", str(repo)]), 0)
        self.assertIn("  registry: line 'newmodel' wire 'gpt-new' is absent", out.getvalue())


class RetargetNoteTests(unittest.TestCase):
    """An orphan in the chosen scope: promote prints the retarget note."""

    def setUp(self) -> None:
        self.raw = catalog.load_raw(FIXTURE_ROOT)["docs"]
        self.providers = self.raw["providers"]["providers"]
        self.lines = self.raw["models"]["models"]

    def _key(self, mode: str) -> str:
        return sorted(
            key for key, line in self.lines.items()
            if catalog.effort_mode(self.providers[line["provider"]]) == mode
        )[0]

    def test_gateway_effort_move_is_noted(self) -> None:
        key = self._key("gateway")
        after = copy.deepcopy(self.lines)
        after[key]["wire_model"] = "next-wire"
        after[key]["generation"] = "99"
        notes = dev.gateway_effort_moves(self.lines, after, self.providers)
        self.assertEqual(len(notes), 1)
        self.assertTrue(
            notes[0].startswith(
                f"running sessions of {key} retarget at the next gateway reload"
            ),
            notes[0],
        )
        self.assertIn("next-wire 99", notes[0])

    def test_client_effort_moves_new_and_unchanged_lines_are_silent(self) -> None:
        key = self._key("client")
        after = copy.deepcopy(self.lines)
        after[key]["wire_model"] = "claude-next"
        after[key]["generation"] = "99"
        after["brand-new"] = copy.deepcopy(self.lines[self._key("gateway")])
        self.assertEqual(dev.gateway_effort_moves(self.lines, after, self.providers), [])
        self.assertEqual(dev.gateway_effort_moves(self.lines, self.lines, self.providers), [])

    @uses_shipped_catalog
    def test_shipped_sonnet_generation_move_is_silent(self) -> None:
        """The shipped client-effort Sonnet move (retired
        history -> current line) prints no gateway retarget/continuity note."""
        shipped = catalog.load_raw(RESOURCES_ROOT)["docs"]
        lines = shipped["models"]["models"]
        providers = shipped["providers"]["providers"]
        history = next(row for rkey, row in shipped["retired"]["retired"].items()
                       if rkey.startswith("sonnet@") and row.get("successor") == "sonnet")
        before = copy.deepcopy(lines)
        (selector, _contract), = history["selectors"].items()
        before["sonnet"].update(wire_model=history["last_wire"], generation=history["generation"],
                                selector=selector)
        self.assertEqual(catalog.effort_mode(providers[lines["sonnet"]["provider"]]), "client")
        self.assertEqual(dev.gateway_effort_moves(before, lines, providers), [])

    def test_promote_returns_and_prints_notes_against_the_running_catalog(self) -> None:
        root = Path(tempfile.mkdtemp(prefix="claude-multi-retarget-"))
        os.chmod(root, 0o700)
        self.addCleanup(lambda: shutil.rmtree(root, ignore_errors=True))
        repo = fake_checkout(root / "repo", FIXTURE_ROOT)
        key = self._key("gateway")
        running = copy.deepcopy(self.lines)
        running[key]["wire_model"] = "older-wire"
        running[key]["generation"] = "0.9"
        draft = dev.make_model_draft(
            name="d1",
            provider="openai",
            entry={
                "id": "newmodel", "provider": "openai", "display": "New Model",
                "generation": "1", "wire_model": "gpt-new", "capabilities": ["agents"],
                "roles": ["cm-reviewer"],
                "context": {
                    "client_tokens": 128000, "provider_tokens": 128000,
                    "scalar_tokens": 128000, "ordinary_profile": None,
                    "declared_tokens": 128000, "validated_tokens": 128000,
                    "qualification": "retarget test fixture",
                },
                "efforts": {"high": {"selector": "gpt-multi-newmodel-high",
                                     "proxy_contract": "reasoning-effort-high"}},
                "default_effort": "high", "lead": None,
                "routing_note": "Fixture model for the retarget note.",
                "minimum_tested": {"claude_code": "2.1.216", "cliproxyapi": "7.3.15"},
                "status": "new", "registry_overlay": None,
            },
            now="2026-09-26T00:00:00Z",
        )
        record = dev.review_draft(
            draft, draft_name="d1", repo=repo, revision="deadbeef",
            now="2026-09-26T00:00:00Z",
            runner=lambda c, w: {"cmd": c, "returncode": 0},
            candidate_parent=Path(tempfile.mkdtemp(dir=root)),
        )
        # Without a running catalog the draft's own effect is compared: a
        # new line is never a move.
        patch_path, notes = dev.promote_patch_output(
            draft, repo=repo, output=root / "out.diff"
        )
        self.assertEqual(notes, [])
        self.assertTrue(patch_path.exists())
        self.assertEqual(
            len(dev.gateway_effort_moves(running, self.lines, self.providers)), 1
        )
        # The CLI compares against the installed (running) catalog and
        # prints each note after the promotion.
        store = dev.DraftStore(root / "state" / "claude-multi" / "drafts")
        store.save("d1", draft)
        from claude_multi import state, strict_json

        state.atomic_write(
            store.root / "d1.review.json", strict_json.canonical_file_bytes(record)
        )
        out = io.StringIO()
        with mock.patch.dict(os.environ, {"XDG_STATE_HOME": str(root / "state")}), \
                mock.patch.object(dev, "running_catalog_lines", return_value=running), \
                redirect_stdout(out):
            self.assertEqual(dev.main(["promote", "d1", "--repo", str(repo)]), 0)
        notes = [line for line in out.getvalue().splitlines() if line.startswith("note: ")]
        self.assertEqual(len(notes), 1)
        self.assertTrue(
            notes[0].startswith(
                f"note: running sessions of {key} retarget at the next gateway reload"
            ),
            notes,
        )
        post = json.loads((repo / dev.RESOURCES / "catalog" / "models.json").read_text())
        self.assertEqual(post["models"]["newmodel"]["status"], "new")


class GenerationMoveTests(unittest.TestCase):
    setUp = RetargetNoteTests.setUp
    def _key(self, mode):
        return next(key for key, entry in sorted(self.lines.items())
                    if catalog.effort_mode(self.providers[entry["provider"]]) == mode and len(entry["efforts"]) >= 2)

    def test_renamed_aliases_are_not_live_retargets(self) -> None:
        key = self._key("gateway")
        after = copy.deepcopy(self.lines)
        after[key].update(wire_model="fixture-next-wire", generation="99")
        for level, spec in after[key]["efforts"].items():
            spec["selector"] = f"gpt-multi-{key}-99-{level}[1m]"
        notes = dev.gateway_effort_moves(self.lines, after, self.providers)
        self.assertEqual(len(notes), 1)
        self.assertIn("continuity until resume", notes[0])
        self.assertNotIn("retarget", notes[0])
        with self.assertRaisesRegex(dev.DevError, "--from-json"):
            docs = copy.deepcopy(self.raw)
            docs["models"]["models"] = after
            dev._scaffold_model_entry(docs, like_id=key, new_id="fixture-new", wire_model="fixture-new-wire")

    def test_partial_rename_and_client_suffix_change_are_not_misreported(self) -> None:
        key = self._key("gateway")
        after = copy.deepcopy(self.lines)
        after[key].update(wire_model="fixture-next-wire", generation="99")
        levels = list(after[key]["efforts"])
        self.assertGreaterEqual(len(levels), 2)
        after[key]["efforts"][levels[0]]["selector"] = "gpt-multi-fixture-renamed"
        notes = dev.gateway_effort_moves(self.lines, after, self.providers)
        self.assertEqual(len(notes), 2)
        self.assertIn("retarget", notes[0])
        self.assertIn("continuity until resume", notes[1])
        after = copy.deepcopy(self.lines)
        after[key].update(wire_model="fixture-next-wire", generation="99")
        for spec in after[key]["efforts"].values():
            spec["selector"] = spec["selector"].removesuffix("[1m]")
        notes = dev.gateway_effort_moves(self.lines, after, self.providers)
        self.assertEqual(len(notes), 1)
        self.assertIn("retarget", notes[0])


if __name__ == "__main__":
    unittest.main()
