"""The gateway's licence notices, SBOMs and contract stay in step with the recipe.

gateway/licenses/, gateway/sbom/ and the packaged resource
src/claude_multi/data/gateway-contract.json are generated by tools/build.py
(`gateway notices`, `gateway contract`). These
checks need no Go toolchain or network: everything derivable from the
checked-in recipe and patches is re-rendered and compared byte for byte, the
recorded build inputs must be the recipe's, and every listed text must carry
its recorded sha256. What only a build can show (the modules each binary
links, the vendored texts) is checked by the record step of every build, and
here against built binaries when CLAUDE_MULTI_TEST_DIST_GATEWAY or
CLAUDE_MULTI_TEST_NIX_GATEWAY names them.
"""

from __future__ import annotations

import base64
import hashlib
import importlib.util
import json
import os
import unittest
from pathlib import Path

from _layout import (BUILD_TOOL, FIXTURES_ROOT, GATEWAY_CONTRACT, LICENSES_DIR, NIX_DIR, PATCH_DIR, RESOURCES_ROOT,
                     SBOM_DIR, UPSTREAM_JSON)

NIX_GATEWAY_ENV = "CLAUDE_MULTI_TEST_NIX_GATEWAY"
DIST_GATEWAY_ENV = "CLAUDE_MULTI_TEST_DIST_GATEWAY"


def load_tool():
    spec = importlib.util.spec_from_file_location("gateway_build_tool_third_party_notices", BUILD_TOOL)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


tool = load_tool()


def recipe():
    return json.loads(UPSTREAM_JSON.read_text())


def admitted():
    return [entry for entry in recipe()["series"] if entry["admitted"]]


def shipped():
    return [target for target in recipe()["targets"] if target["shipped"]]


def tree():
    return tool.read_notice_tree(LICENSES_DIR)


class InventoryTests(unittest.TestCase):
    def test_inventory_names_the_recipes_inputs_and_series(self):
        doc, inventory = recipe(), tree().inventory
        self.assertEqual(inventory["format"], 1)
        self.assertEqual(inventory["inputs"]["series"], [f"{entry['basename']}@{entry['sha256']}" for entry in admitted()])
        self.assertEqual(inventory["inputs"]["source_tree_sha256"], doc["source"]["tree_sha256"])
        self.assertEqual(inventory["inputs"]["vendor_tree_sha256"], doc["vendor"]["tree_sha256"])
        self.assertRegex(inventory["inputs"]["post_apply_tree_sha256"], r"^[0-9a-f]{64}$")
        self.assertEqual(inventory["toolchain"]["version"], doc["toolchain"]["version"])
        self.assertEqual({key: inventory["upstream"][key] for key in ("name", "version", "commit", "repository", "license")},
                         {key: doc["upstream"][key] for key in ("name", "version", "commit", "repository", "license")})
        self.assertEqual(inventory["targets"], sorted(target["name"] for target in shipped()))
        self.assertEqual(tool.inventory_bytes(inventory), (LICENSES_DIR / "modules.json").read_bytes())

    def test_every_listed_text_carries_its_hash_and_nothing_else_is_there(self):
        notices = tree()
        inventory = notices.inventory
        recorded = {entry["path"]: entry["sha256"] for entry in
                    inventory["upstream"]["files"] + inventory["toolchain"]["files"] + [inventory["upstream"]["modifications"]]
                    + [item for module in inventory["modules"] for item in module["files"]]}
        for path, raw in notices.files.items():
            with self.subTest(path=path):
                self.assertEqual(hashlib.sha256(raw).hexdigest(), recorded[path])
        present = {path.relative_to(LICENSES_DIR).as_posix() for path in LICENSES_DIR.rglob("*") if path.is_file()}
        allowed = set(recorded) | {"modules.json"} | ({"license-overrides.json"} if (LICENSES_DIR / "license-overrides.json").exists() else set())
        self.assertEqual(present, allowed)

    def test_modules_are_sorted_hashed_and_cover_shipped_targets_only(self):
        modules = tree().inventory["modules"]
        self.assertTrue(modules)
        self.assertEqual([(module["path"], module["version"]) for module in modules],
                         sorted((module["path"], module["version"]) for module in modules))
        names = {target["name"] for target in shipped()}
        for module in modules:
            with self.subTest(module=module["path"]):
                self.assertTrue(module["targets"])
                self.assertLessEqual(set(module["targets"]), names)
                self.assertEqual(len(base64.b64decode(module["sum"].removeprefix("h1:"), validate=True)), 32)
                self.assertTrue(module["sum"].startswith("h1:"))

    def test_licences_classify_as_recorded(self):
        notices = tree()
        inventory = notices.inventory
        overrides = tool.read_overrides(LICENSES_DIR / "license-overrides.json")
        for module in inventory["modules"]:
            with self.subTest(module=module["path"]):
                if any(entry["kind"] == "license" for entry in module["files"]):
                    self.assertNotIn(module["path"], overrides)
                    self.assertNotIn("license_override", module)
                    self.assertEqual(tool.license_of(module["files"], notices.files), module["license"])
                else:
                    # Only a module that ships no licence text has an override.
                    self.assertEqual(module["license"], overrides[module["path"]]["license"])
                    self.assertEqual(module["license_override"], overrides[module["path"]]["reason"])
        self.assertLessEqual(set(overrides), {module["path"] for module in inventory["modules"]})
        self.assertEqual(tool.license_of(inventory["toolchain"]["files"], notices.files), inventory["toolchain"]["license"])
        self.assertEqual(inventory["upstream"]["license"], recipe()["upstream"]["license"])
        self.assertEqual(tool.license_of(inventory["upstream"]["files"], notices.files), inventory["upstream"]["license"])

    def test_the_notice_texts_modules_ship_are_reproduced(self):
        # Apache-2.0 section 4(d): a module's NOTICE travels with it; the two
        # linked modules that ship one today are named here on purpose.
        modules = {module["path"]: module for module in tree().inventory["modules"]}
        for path in ("github.com/minio/minio-go/v7", "gopkg.in/yaml.v3"):
            with self.subTest(module=path):
                kinds = [entry["kind"] for entry in modules[path]["files"]]
                self.assertIn("notice", kinds)
        notices = tool.render_third_party_notices(tree()).decode()
        for module in modules.values():
            for entry in module["files"]:
                self.assertIn(tree().files[entry["path"]].decode("utf-8", "replace").strip()[:200], notices)

    def test_subpackage_licences_are_reproduced_at_their_package_paths(self):
        # A linked subpackage may carry its own licence and copyright (utls's
        # dicttls is BSD-3-Clause under a different author than its module);
        # it travels with its module under the package-relative path.
        notices = tree()
        modules = {module["path"]: module for module in notices.inventory["modules"]}
        nested = "modules/github.com/refraction-networking/utls/dicttls/LICENSE"
        self.assertIn(nested, [entry["path"] for entry in modules["github.com/refraction-networking/utls"]["files"]])
        self.assertNotEqual(notices.files[nested], notices.files["modules/github.com/refraction-networking/utls/LICENSE"])
        rendered = tool.render_third_party_notices(notices).decode()
        self.assertIn("== dicttls/LICENSE\n\n" + notices.files[nested].decode().strip()[:120], rendered)
        for module in notices.inventory["modules"]:
            for entry in module["files"]:
                with self.subTest(path=entry["path"]):
                    self.assertTrue(entry["path"].startswith(f"modules/{module['path']}/"))
                    self.assertIsNotNone(tool.notice_kind(entry["path"].rsplit("/", 1)[-1]))

    def test_modifications_list_every_patch_and_file_in_order(self):
        series = [{"basename": entry["basename"], "sha256": entry["sha256"],
                   "files": tool.patch_files((PATCH_DIR / entry["basename"]).read_text(encoding="utf-8"))}
                  for entry in admitted()]
        expected = tool.render_modifications(recipe(), series)
        self.assertEqual(tree().files[tree().inventory["upstream"]["modifications"]["path"]], expected)
        text = expected.decode()
        positions = [text.index(entry["basename"]) for entry in admitted()]
        self.assertEqual(positions, sorted(positions))
        for entry in admitted():
            self.assertIn("sha256 " + entry["sha256"], text)


class SbomTests(unittest.TestCase):
    def test_each_shipped_target_has_its_rendered_sbom_and_nothing_else(self):
        doc, inventory = recipe(), tree().inventory
        self.assertEqual(sorted(path.name for path in SBOM_DIR.iterdir()),
                         sorted(target["name"] + ".cdx.json" for target in shipped()))
        for target in shipped():
            with self.subTest(target=target["name"]):
                self.assertEqual((SBOM_DIR / (target["name"] + ".cdx.json")).read_bytes(),
                                 tool.render_sbom(doc, inventory, target))

    def test_sbom_content(self):
        doc, inventory = recipe(), tree().inventory
        for target in shipped():
            with self.subTest(target=target["name"]):
                bom = json.loads((SBOM_DIR / (target["name"] + ".cdx.json")).read_text())
                self.assertEqual((bom["bomFormat"], bom["specVersion"], bom["version"]), ("CycloneDX", "1.6", 1))
                self.assertRegex(bom["serialNumber"], r"^urn:uuid:[0-9a-f-]{36}$")
                self.assertNotIn("timestamp", bom["metadata"])
                linked = [module for module in inventory["modules"] if target["name"] in module["targets"]]
                components = bom["components"]
                self.assertEqual(len(components), len(linked) + 1)
                for module, component in zip(linked, components):
                    self.assertEqual((component["name"], component["version"]), (module["path"], module["version"]))
                    self.assertEqual(component["hashes"], [{"alg": "SHA-256", "content": base64.b64decode(
                        module["sum"].removeprefix("h1:")).hex()}])
                self.assertEqual(components[-1]["version"], "go" + doc["toolchain"]["version"])
                self.assertEqual(bom["dependencies"], [{"ref": doc["upstream"]["binary"],
                                                        "dependsOn": [item["bom-ref"] for item in components]}])
                main = bom["metadata"]["component"]
                pedigree = main["pedigree"]
                self.assertEqual(pedigree["commits"][0]["uid"], doc["upstream"]["commit"])
                self.assertEqual([patch["diff"]["url"].rsplit("/", 1)[-1] for patch in pedigree["patches"]],
                                 [entry["basename"] for entry in admitted()])
                properties = [(item["name"].removeprefix("claude-multi:gateway:"), item["value"]) for item in main["properties"]]
                self.assertEqual([value for name, value in properties if name == "patch"], inventory["inputs"]["series"])
                values = dict(properties)
                self.assertEqual(values["post-apply-tree-sha256"], inventory["inputs"]["post_apply_tree_sha256"])
                self.assertEqual(values["target"], target["name"])
                self.assertEqual(values["ldflags"], " ".join(doc["build"]["ldflags"]))
                self.assertEqual(values["build-env"], "CGO_ENABLED=0")

    def test_serial_number_follows_the_content(self):
        doc, inventory = recipe(), tree().inventory
        target = shipped()[0]
        first = json.loads(tool.render_sbom(doc, inventory, target))
        changed = json.loads(json.dumps(inventory))
        changed["inputs"]["post_apply_tree_sha256"] = "0" * 64
        second = json.loads(tool.render_sbom(doc, changed, target))
        self.assertNotEqual(first["serialNumber"], second["serialNumber"])
        self.assertEqual(json.loads(tool.render_sbom(doc, inventory, target)), first)


class ContractTests(unittest.TestCase):
    def test_contract_is_the_recipes_admitted_series_in_nix_form(self):
        from claude_multi import qualify

        raw = GATEWAY_CONTRACT.read_bytes()
        doc = recipe()
        for entry in admitted():
            self.assertEqual(hashlib.sha256((PATCH_DIR / entry["basename"]).read_bytes()).hexdigest(), entry["sha256"])
        expected = {"version": 1, "upstream_version": doc["upstream"]["version"],
                    "patches": [f"{entry['basename']}@{entry['sha256']}" for entry in admitted()]}
        # builtins.toJSON: sorted keys, no whitespace, no trailing newline.
        self.assertEqual(raw, json.dumps(expected, sort_keys=True, separators=(",", ":")).encode())
        self.assertEqual(raw, tool.contract_bytes(tool.contract_document(doc, admitted())))
        self.assertEqual(qualify.parse_gateway_contract(raw), expected)
        self.assertEqual(json.loads(raw)["patches"], tree().inventory["inputs"]["series"])

    def test_nix_refuses_a_contract_that_differs_from_its_passthru(self):
        # One content authority: the recipe's contract; the gateway derivation
        # and the package both refuse a checked-in copy that differs from it.
        text = (NIX_DIR / "gateway.nix").read_text()
        self.assertIn("builtins.toJSON contract == builtins.readFile ../src/claude_multi/data/gateway-contract.json",
                      text)
        self.assertIn("gateway-contract.json is stale: run python3 tools/build.py gateway contract", text)
        self.assertIn("--licenses ${licenses} --sbom ${sbom}", text)
        package = (NIX_DIR / "package.nix").read_text()
        self.assertIn("builtins.toJSON cliProxyApiContract == builtins.readFile "
                      "../src/claude_multi/data/gateway-contract.json", package)
        self.assertNotIn("writeText \"gateway-contract.json\"", package)  # no second, generated copy
        self.assertEqual(tool.DEFAULT_CONTRACT, GATEWAY_CONTRACT)
        self.assertEqual(GATEWAY_CONTRACT, RESOURCES_ROOT / "gateway-contract.json")

    def test_the_source_tree_resolves_the_packaged_gateway_identity(self):
        # The checked-in contract is a packaged resource: a source launch now
        # binds evidence to the same gateway identity an installed package
        # does (it was absent before the contract became package data).
        from claude_multi import assets, qualify, strict_json

        native = strict_json.load(RESOURCES_ROOT / "catalog" / "native-contract.json")
        expected = qualify.gateway_contract_digest(qualify.parse_gateway_contract(GATEWAY_CONTRACT.read_bytes()))
        self.assertEqual(qualify.contract_identity(native, assets.root(environ={})).gateway, expected)
        # Resources without a contract, or with an invalid one, stay absent.
        self.assertIsNone(qualify.contract_identity(native, FIXTURES_ROOT / "assets").gateway)
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            (Path(tmp) / "gateway-contract.json").write_text('{"version": 1}')
            self.assertIsNone(qualify.contract_identity(native, tmp).gateway)


class BuiltBinaryTests(unittest.TestCase):
    """The modules a built gateway links are the recorded ones (no Go needed)."""

    def binaries(self):
        found = []
        if os.environ.get(DIST_GATEWAY_ENV):
            dist = Path(os.environ[DIST_GATEWAY_ENV])
            found += [(target["name"], dist / target["name"] / "cli-proxy-api") for target in shipped()
                      if (dist / target["name"] / "cli-proxy-api").is_file()]
        if os.environ.get(NIX_GATEWAY_ENV):
            output = Path(os.environ[NIX_GATEWAY_ENV])
            build = json.loads((output / "share" / "cli-proxy-api" / "BUILD.json").read_text())
            found += [(name, output / "bin" / "cli-proxy-api") for name in build["targets"]]
        return found

    def test_linked_modules_match_the_inventory(self):
        binaries = self.binaries()
        if not binaries:
            self.skipTest(f"BOUNDARY: set {DIST_GATEWAY_ENV} (a tools/build.py dist directory) or "
                          f"{NIX_GATEWAY_ENV} (a Nix gateway output) to check built binaries")
        inventory = tree().inventory
        for name, path in binaries:
            with self.subTest(target=name, binary=str(path)):
                version, modinfo = tool.go_buildinfo(path.read_bytes())
                self.assertEqual(version, "go" + inventory["toolchain"]["version"])
                self.assertEqual(sorted(tool.linked_modules(modinfo)),
                                 sorted((module["path"], module["version"]) for module in inventory["modules"]
                                        if name in module["targets"]))


if __name__ == "__main__":
    unittest.main()
